version: '3.9'

volumes:
  postgres_volume:

services:
  backend-postgres:
    image: postgres:14-alpine3.17
    env_file:
      - backend.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend-migrator-postgres:
    container_name: backend-migrator-postgres
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: backend-postgres
    depends_on:
      - backend-postgres

  backend-nats:
    image: nats-streaming:0.25.6-alpine3.18
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"

  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "30016:30016"
    environment:
      DB_HOST: backend-postgres
      DB_PORT: "5432"
      NATS_HOST: backend-nats
      NATS_PORT: "4222"
    depends_on:
      - backend-postgres
      - backend-nats
      - backend-migrator-postgres

  nuxt:
    container_name: nuxt
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '3000:3000'
    restart: always