version: '3'

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  nats:
    image: nats-streaming:0.25.6-alpine3.18
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"